remote_theme: mmistakes/minimal-mistakes 
plugins: 
  - jekyll-remote-theme 
title: RGHIKE 
description: Dedicated to RG backpacking trips, bushwhacks, and trailruns 
url: "https://pucksly123.github.io" 
baseurl: "/RGHIKE"
